(venv) sick7@raspberrypi:~/SICK/SICK-Capstone/pi_stuff $ python3 tim240_run.py
Traceback (most recent call last):
  File "/home/sick7/SICK/SICK-Capstone/pi_stuff/tim240_run.py", line 495, in <module>
    main()
    ~~~~^^
  File "/home/sick7/SICK/SICK-Capstone/pi_stuff/tim240_run.py", line 332, in main
    GPIO.setup(DETECTION_GPIO_PIN, GPIO.OUT)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Cannot determine SOC peripheral base address
(venv) sick7@raspberrypi:~/SICK/SICK-Capstone/pi_stuff $ python3 tim240_run.py
Traceback (most recent call last):
  File "/home/sick7/SICK/SICK-Capstone/pi_stuff/tim240_run.py", line 495, in <module>
    main()
    ~~~~^^
  File "/home/sick7/SICK/SICK-Capstone/pi_stuff/tim240_run.py", line 332, in main
    GPIO.setup(DETECTION_GPIO_PIN, GPIO.OUT)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Cannot determine SOC peripheral base address
